/**
 * Knowledge Items (KI) System
 *
 * Persistent, file-based memory system storing distilled wisdom across sessions.
 * KIs are workspace-scoped and automatically loaded into agent context.
 *
 * Storage: {workspace}/.orch/knowledge/
 *
 * KI Types:
 * - architecture.md    — High-level system design, component relationships
 * - patterns.md        — Code patterns, conventions used in this codebase
 * - db_schema.md       — Database schema, relationships, migrations
 * - api_spec.md        — API endpoints, request/response formats
 * - dependencies.md    — Key dependencies, versions, upgrade notes
 * - gotchas.md         — Common pitfalls, edge cases, workarounds
 * - decisions.md       — ADRs (Architectural Decision Records)
 * - testing.md         — Test patterns, coverage requirements, mocking strategies
 * - deployment.md      — Build, deploy, CI/CD pipeline information
 * - custom/*.md        — User-defined knowledge items
 *
 * Auto-Discovery:
 * - Scans workspace for common files (README, package.json, etc.)
 * - Extracts key information to bootstrap KIs
 * - Updates KIs when relevant files change
 */

import * as fs from 'node:fs';
import * as path from 'node:path';

// ============================================================================
// Types
// ============================================================================

export interface KnowledgeItem {
  /** Unique identifier (filename without extension) */
  id: string;
  /** Display name */
  name: string;
  /** Category for grouping */
  category: KICategory;
  /** The actual content */
  content: string;
  /** File path relative to .orch/knowledge/ */
  relativePath: string;
  /** Absolute file path */
  absolutePath: string;
  /** Last modified timestamp */
  updatedAt: number;
  /** Estimated token count */
  tokenEstimate: number;
  /** Priority for context injection (higher = more important) */
  priority: number;
  /** Tags for filtering */
  tags: string[];
  /** Whether this was auto-generated or user-created */
  isAutoGenerated: boolean;
}

export type KICategory =
  | 'architecture'
  | 'patterns'
  | 'database'
  | 'api'
  | 'dependencies'
  | 'gotchas'
  | 'decisions'
  | 'testing'
  | 'deployment'
  | 'custom';

export interface KIManagerConfig {
  workspacePath: string;
  /** Max tokens to allocate to KIs in context */
  maxContextTokens: number;
  /** Whether to auto-discover and generate KIs */
  enableAutoDiscovery: boolean;
}

export interface KIContextSelection {
  /** Selected KIs to inject into context */
  items: KnowledgeItem[];
  /** Total tokens used */
  totalTokens: number;
  /** KIs that were available but not selected */
  skipped: string[];
}

// ============================================================================
// Constants
// ============================================================================

const KI_DIR_NAME = '.orch';
const KNOWLEDGE_DIR_NAME = 'knowledge';
const CUSTOM_DIR_NAME = 'custom';

const DEFAULT_KI_PRIORITY: Record<KICategory, number> = {
  architecture: 100,
  patterns: 90,
  database: 80,
  api: 70,
  dependencies: 60,
  gotchas: 95, // High priority - prevents common mistakes
  decisions: 50,
  testing: 40,
  deployment: 30,
  custom: 55,
};

/** Files to scan for auto-discovery */


// ============================================================================
// KI Manager Class
// ============================================================================

export class KnowledgeItemManager {
  private workspacePath: string;
  private kiPath: string;
  private config: KIManagerConfig;
  private cache: Map<string, KnowledgeItem> = new Map();
  private lastScan = 0;
  private scanInterval = 30000; // 30 seconds

  constructor(config: KIManagerConfig) {
    this.workspacePath = config.workspacePath;
    this.kiPath = path.join(config.workspacePath, KI_DIR_NAME, KNOWLEDGE_DIR_NAME);
    this.config = config;
  }

  // ==========================================================================
  // Initialization
  // ==========================================================================

  /**
   * Initialize the KI system for this workspace.
   * Creates directories and performs initial scan.
   */
  async initialize(): Promise<void> {
    // Ensure directories exist
    this.ensureDirectories();

    // Scan existing KIs
    await this.scanKnowledgeItems();

    // Auto-discover if enabled and no KIs exist
    if (this.config.enableAutoDiscovery && this.cache.size === 0) {
      await this.autoDiscover();
    }
  }

  /**
   * Ensure the .orch/knowledge directory structure exists.
   */
  private ensureDirectories(): void {
    const dirs = [
      path.join(this.workspacePath, KI_DIR_NAME),
      this.kiPath,
      path.join(this.kiPath, CUSTOM_DIR_NAME),
    ];

    for (const dir of dirs) {
      if (!fs.existsSync(dir)) {
        fs.mkdirSync(dir, { recursive: true });
      }
    }

    // Create .gitignore to exclude session data but include knowledge
    const gitignorePath = path.join(this.workspacePath, KI_DIR_NAME, '.gitignore');
    if (!fs.existsSync(gitignorePath)) {
      fs.writeFileSync(gitignorePath, `# Exclude session data, include knowledge
sessions/
*.log
*.tmp

# Include knowledge items
!knowledge/
`, 'utf-8');
    }
  }

  // ==========================================================================
  // Scanning & Loading
  // ==========================================================================

  /**
   * Scan the knowledge directory for all KI files.
   */
  async scanKnowledgeItems(): Promise<KnowledgeItem[]> {
    this.cache.clear();

    if (!fs.existsSync(this.kiPath)) {
      return [];
    }

    const items: KnowledgeItem[] = [];

    // Scan root KI files
    const rootFiles = fs.readdirSync(this.kiPath).filter(f => f.endsWith('.md') && !f.startsWith('.'));
    for (const file of rootFiles) {
      const ki = this.loadKIFile(path.join(this.kiPath, file), file);
      if (ki) {
        items.push(ki);
        this.cache.set(ki.id, ki);
      }
    }

    // Scan custom directory
    const customPath = path.join(this.kiPath, CUSTOM_DIR_NAME);
    if (fs.existsSync(customPath)) {
      const customFiles = fs.readdirSync(customPath).filter(f => f.endsWith('.md'));
      for (const file of customFiles) {
        const ki = this.loadKIFile(
          path.join(customPath, file),
          `${CUSTOM_DIR_NAME}/${file}`,
          'custom'
        );
        if (ki) {
          items.push(ki);
          this.cache.set(ki.id, ki);
        }
      }
    }

    this.lastScan = Date.now();
    return items;
  }

  /**
   * Load a single KI file.
   */
  private loadKIFile(
    absolutePath: string,
    relativePath: string,
    forceCategory?: KICategory
  ): KnowledgeItem | null {
    try {
      const content = fs.readFileSync(absolutePath, 'utf-8');
      const stat = fs.statSync(absolutePath);
      const filename = path.basename(relativePath, '.md');

      // Parse front matter if present
      const { metadata, body } = this.parseFrontMatter(content);

      // Determine category from filename or front matter
      const categoryValue = forceCategory || (metadata.category as KICategory | undefined) || this.inferCategory(filename);

      // Extract tags from front matter or content
      const tagsValue = Array.isArray(metadata.tags) ? (metadata.tags as string[]) : this.extractTags(body);

      // Estimate tokens (rough: ~4 chars per token)
      const tokenEstimate = Math.ceil(body.length / 4);

      return {
        id: filename,
        name: (metadata.name as string | undefined) || this.prettifyName(filename),
        category: categoryValue,
        content: body,
        relativePath,
        absolutePath,
        updatedAt: stat.mtimeMs,
        tokenEstimate,
        priority: (metadata.priority as number | undefined) ?? DEFAULT_KI_PRIORITY[categoryValue],
        tags: tagsValue,
        isAutoGenerated: (metadata.auto_generated as boolean | undefined) ?? false,
      };
    } catch (error) {
      console.error(`[KI] Failed to load ${absolutePath}:`, error);
      return null;
    }
  }

  /**
   * Parse YAML front matter from markdown content.
   */
  private parseFrontMatter(content: string): {
    metadata: Record<string, unknown>;
    body: string;
  } {
    const frontMatterRegex = /^---\n([\s\S]*?)\n---\n/;
    const match = content.match(frontMatterRegex);

    if (!match) {
      return { metadata: {}, body: content };
    }

    const body = content.slice(match[0].length);
    const metadata: Record<string, unknown> = {};

    // Simple YAML parsing (key: value pairs)
    const lines = match[1].split('\n');
    for (const line of lines) {
      const colonIdx = line.indexOf(':');
      if (colonIdx > 0) {
        const key = line.slice(0, colonIdx).trim();
        let value: unknown = line.slice(colonIdx + 1).trim();

        // Parse arrays
        if (value === '') {
          continue;
        }
        if (String(value).startsWith('[') && String(value).endsWith(']')) {
          value = String(value).slice(1, -1).split(',').map(s => s.trim().replace(/"/g, ''));
        }
        // Parse numbers
        else if (!isNaN(Number(value))) {
          value = Number(value);
        }
        // Parse booleans
        else if (value === 'true') value = true;
        else if (value === 'false') value = false;

        metadata[key] = value;
      }
    }

    return { metadata, body };
  }

  /**
   * Infer category from filename.
   */
  private inferCategory(filename: string): KICategory {
    const lower = filename.toLowerCase();

    if (lower.includes('arch') || lower.includes('design') || lower.includes('overview')) {
      return 'architecture';
    }
    if (lower.includes('pattern') || lower.includes('convention') || lower.includes('style')) {
      return 'patterns';
    }
    if (lower.includes('db') || lower.includes('schema') || lower.includes('database') || lower.includes('model')) {
      return 'database';
    }
    if (lower.includes('api') || lower.includes('endpoint') || lower.includes('route')) {
      return 'api';
    }
    if (lower.includes('dep') || lower.includes('package') || lower.includes('require')) {
      return 'dependencies';
    }
    if (lower.includes('gotcha') || lower.includes('pitfall') || lower.includes('warning') || lower.includes('caveat')) {
      return 'gotchas';
    }
    if (lower.includes('decision') || lower.includes('adr')) {
      return 'decisions';
    }
    if (lower.includes('test') || lower.includes('spec') || lower.includes('mock')) {
      return 'testing';
    }
    if (lower.includes('deploy') || lower.includes('ci') || lower.includes('build') || lower.includes('release')) {
      return 'deployment';
    }

    return 'custom';
  }

  /**
   * Extract tags from content (words after # in headings).
   */
  private extractTags(content: string): string[] {
    const tags = new Set<string>();

    // Extract from headings
    const headingMatches = content.matchAll(/^#+\s+(.+)$/gm);
    for (const match of headingMatches) {
      const words = match[1].toLowerCase().split(/\s+/);
      words.forEach(w => {
        if (w.length > 3 && !['the', 'and', 'for', 'with', 'this', 'that'].includes(w)) {
          tags.add(w.replace(/[^a-z0-9]/g, ''));
        }
      });
    }

    return Array.from(tags).slice(0, 10);
  }

  /**
   * Convert filename to display name.
   */
  private prettifyName(filename: string): string {
    return filename
      .replace(/_/g, ' ')
      .replace(/-/g, ' ')
      .split(' ')
      .map(w => w.charAt(0).toUpperCase() + w.slice(1))
      .join(' ');
  }

  // ==========================================================================
  // Context Selection
  // ==========================================================================

  /**
   * Select KIs to inject into context based on relevance and budget.
   */
  selectForContext(
    query = '',
    maxTokens?: number
  ): KIContextSelection {
    const budget = maxTokens ?? this.config.maxContextTokens;

    // Refresh cache if stale
    if (Date.now() - this.lastScan > this.scanInterval) {
      this.scanKnowledgeItems();
    }

    const allKIs = Array.from(this.cache.values());

    // Score each KI based on priority and query relevance
    const scored = allKIs.map(ki => ({
      ki,
      score: this.scoreKI(ki, query),
    }));

    // Sort by score descending
    scored.sort((a, b) => b.score - a.score);

    // Select KIs within budget
    const selected: KnowledgeItem[] = [];
    const skipped: string[] = [];
    let totalTokens = 0;

    for (const { ki } of scored) {
      if (totalTokens + ki.tokenEstimate <= budget) {
        selected.push(ki);
        totalTokens += ki.tokenEstimate;
      } else {
        skipped.push(ki.id);
      }
    }

    return { items: selected, totalTokens, skipped };
  }

  /**
   * Score a KI for context selection.
   */
  private scoreKI(ki: KnowledgeItem, query: string): number {
    let score = ki.priority;

    // Boost for query relevance
    if (query) {
      const queryLower = query.toLowerCase();
      const contentLower = ki.content.toLowerCase();

      // Check tags
      for (const tag of ki.tags) {
        if (queryLower.includes(tag)) {
          score += 20;
        }
      }

      // Check content for query keywords
      const queryWords = queryLower.split(/\s+/).filter(w => w.length > 3);
      for (const word of queryWords) {
        if (contentLower.includes(word)) {
          score += 5;
        }
      }

      // Exact phrase match
      if (contentLower.includes(queryLower)) {
        score += 30;
      }
    }

    // Recency bonus (more recently updated = slightly higher score)
    const ageHours = (Date.now() - ki.updatedAt) / (1000 * 60 * 60);
    if (ageHours < 24) {
      score += 10;
    } else if (ageHours < 168) {
      // 1 week
      score += 5;
    }

    return score;
  }

  /**
   * Format selected KIs for injection into system prompt.
   */
  formatForContext(selection: KIContextSelection): string {
    if (selection.items.length === 0) {
      return '';
    }

    const sections: string[] = [
      '<knowledge_base>',
      'The following knowledge items contain important information about this codebase.',
      'Use them to understand patterns, architecture, and conventions.',
      '',
    ];

    // Group by category
    const byCategory = new Map<KICategory, KnowledgeItem[]>();
    for (const ki of selection.items) {
      const cat = byCategory.get(ki.category) || [];
      cat.push(ki);
      byCategory.set(ki.category, cat);
    }

    // Output each category
    const categoryOrder: KICategory[] = [
      'architecture',
      'gotchas',
      'patterns',
      'database',
      'api',
      'dependencies',
      'testing',
      'deployment',
      'decisions',
      'custom',
    ];

    for (const category of categoryOrder) {
      const kis = byCategory.get(category);
      if (!kis || kis.length === 0) continue;

      sections.push(`## ${this.prettifyName(category)}`);
      sections.push('');

      for (const ki of kis) {
        sections.push(`### ${ki.name}`);
        sections.push(ki.content);
        sections.push('');
      }
    }

    sections.push('</knowledge_base>');

    return sections.join('\n');
  }

  // ==========================================================================
  // CRUD Operations
  // ==========================================================================

  /**
   * Get a single KI by ID.
   */
  get(id: string): KnowledgeItem | undefined {
    return this.cache.get(id);
  }

  /**
   * Get all KIs.
   */
  getAll(): KnowledgeItem[] {
    return Array.from(this.cache.values());
  }

  /**
   * Get KIs by category.
   */
  getByCategory(category: KICategory): KnowledgeItem[] {
    return this.getAll().filter(ki => ki.category === category);
  }

  /**
   * Create or update a KI.
   */
  async save(
    id: string,
    content: string,
    options: {
      category?: KICategory;
      name?: string;
      priority?: number;
      tags?: string[];
      isCustom?: boolean;
    } = {}
  ): Promise<KnowledgeItem> {
    const category = options.category || this.inferCategory(id);
    const isCustom = options.isCustom ?? category === 'custom';

    const relativePath = isCustom
      ? `${CUSTOM_DIR_NAME}/${id}.md`
      : `${id}.md`;
    const absolutePath = path.join(this.kiPath, relativePath);

    // Build front matter
    const frontMatter: string[] = ['---'];
    if (options.name) frontMatter.push(`name: ${options.name}`);
    frontMatter.push(`category: ${category}`);
    if (options.priority !== undefined) frontMatter.push(`priority: ${options.priority}`);
    if (options.tags && options.tags.length > 0) {
      frontMatter.push(`tags: [${options.tags.map(t => `"${t}"`).join(', ')}]`);
    }
    frontMatter.push(`updated: ${new Date().toISOString()}`);
    frontMatter.push('---');
    frontMatter.push('');

    const fullContent = frontMatter.join('\n') + content;

    // Ensure directory exists
    const dir = path.dirname(absolutePath);
    if (!fs.existsSync(dir)) {
      fs.mkdirSync(dir, { recursive: true });
    }

    // Write file
    fs.writeFileSync(absolutePath, fullContent, 'utf-8');

    // Reload into cache
    const ki = this.loadKIFile(absolutePath, relativePath);
    if (ki) {
      this.cache.set(ki.id, ki);
      return ki;
    }

    throw new Error(`Failed to save KI: ${id}`);
  }

  /**
   * Delete a KI.
   */
  delete(id: string): boolean {
    const ki = this.cache.get(id);
    if (!ki) return false;

    try {
      fs.unlinkSync(ki.absolutePath);
      this.cache.delete(id);
      return true;
    } catch {
      return false;
    }
  }

  // ==========================================================================
  // Auto-Discovery
  // ==========================================================================

  /**
   * Auto-discover and generate initial KIs from workspace.
   */
  async autoDiscover(): Promise<KnowledgeItem[]> {
    const discovered: KnowledgeItem[] = [];

    // Check for README
    const readmePath = path.join(this.workspacePath, 'README.md');
    if (fs.existsSync(readmePath)) {
      const readme = fs.readFileSync(readmePath, 'utf-8');
      const summary = this.extractProjectSummary(readme);
      if (summary) {
        const ki = await this.save('architecture', summary, {
          name: 'Project Architecture',
          category: 'architecture',
          tags: ['overview', 'readme'],
        });
        discovered.push(ki);
      }
    }

    // Check for package.json (Node.js)
    const packageJsonPath = path.join(this.workspacePath, 'package.json');
    if (fs.existsSync(packageJsonPath)) {
      const pkgJson = JSON.parse(fs.readFileSync(packageJsonPath, 'utf-8'));
      const depsContent = this.formatDependencies(pkgJson);
      if (depsContent) {
        const ki = await this.save('dependencies', depsContent, {
          name: 'Node.js Dependencies',
          category: 'dependencies',
          tags: ['npm', 'nodejs', 'packages'],
        });
        discovered.push(ki);
      }
    }

    // Check for tsconfig.json (TypeScript)
    const tsconfigPath = path.join(this.workspacePath, 'tsconfig.json');
    if (fs.existsSync(tsconfigPath)) {
      const patternsContent = this.extractTypeScriptPatterns(tsconfigPath);
      if (patternsContent) {
        const existing = this.cache.get('patterns');
        const combined = existing
          ? existing.content + '\n\n## TypeScript Configuration\n\n' + patternsContent
          : '# Code Patterns & Conventions\n\n## TypeScript Configuration\n\n' + patternsContent;

        const ki = await this.save('patterns', combined, {
          name: 'Code Patterns',
          category: 'patterns',
          tags: ['typescript', 'conventions'],
        });
        discovered.push(ki);
      }
    }

    // Mark as auto-generated
    for (const ki of discovered) {
      ki.isAutoGenerated = true;
    }

    return discovered;
  }

  /**
   * Extract project summary from README.
   */
  private extractProjectSummary(readme: string): string | null {
    const lines = readme.split('\n');
    const summaryLines: string[] = [];
    let inDescription = false;

    for (const line of lines) {
      // Skip badges
      if (line.includes('![') && line.includes('](')) continue;

      // Start capturing after title
      if (line.startsWith('# ') && !inDescription) {
        summaryLines.push(line);
        inDescription = true;
        continue;
      }

      if (inDescription) {
        // Stop at certain headings
        if (/^##\s+(installation|install|getting started|usage|license|contributing)/i.test(line)) {
          break;
        }

        // Keep description, features, architecture sections
        summaryLines.push(line);

        // Limit length
        if (summaryLines.length > 100) break;
      }
    }

    const summary = summaryLines.join('\n').trim();
    return summary.length > 50 ? summary : null;
  }

  /**
   * Format package.json dependencies for KI.
   */
  private formatDependencies(pkg: Record<string, unknown>): string {
    const sections: string[] = ['# Project Dependencies'];

    if (pkg.name) sections.push(`\nProject: **${pkg.name}** v${pkg.version || '0.0.0'}`);
    if (pkg.description) sections.push(`\n${pkg.description}`);

    const deps = pkg.dependencies as Record<string, string> | undefined;
    const devDeps = pkg.devDependencies as Record<string, string> | undefined;

    if (deps && Object.keys(deps).length > 0) {
      sections.push('\n## Runtime Dependencies\n');
      for (const [name, version] of Object.entries(deps).slice(0, 30)) {
        sections.push(`- \`${name}\`: ${version}`);
      }
    }

    if (devDeps && Object.keys(devDeps).length > 0) {
      sections.push('\n## Dev Dependencies\n');
      for (const [name, version] of Object.entries(devDeps).slice(0, 20)) {
        sections.push(`- \`${name}\`: ${version}`);
      }
    }

    const scripts = pkg.scripts as Record<string, string> | undefined;
    if (scripts && Object.keys(scripts).length > 0) {
      sections.push('\n## Available Scripts\n');
      for (const [name, cmd] of Object.entries(scripts)) {
        sections.push(`- \`npm run ${name}\`: ${cmd}`);
      }
    }

    return sections.join('\n');
  }

  /**
   * Extract TypeScript patterns from tsconfig.
   */
  private extractTypeScriptPatterns(tsconfigPath: string): string {
    try {
      const tsconfig = JSON.parse(fs.readFileSync(tsconfigPath, 'utf-8'));
      const sections: string[] = [];

      const opts = tsconfig.compilerOptions || {};

      if (opts.strict) sections.push('- Strict mode enabled');
      if (opts.target) sections.push(`- Target: ES${opts.target}`);
      if (opts.module) sections.push(`- Module system: ${opts.module}`);
      if (opts.jsx) sections.push(`- JSX: ${opts.jsx}`);
      if (opts.baseUrl) sections.push(`- Base URL: ${opts.baseUrl}`);
      if (opts.paths) {
        sections.push('- Path aliases configured:');
        for (const [alias, paths] of Object.entries(opts.paths as Record<string, string[]>)) {
          sections.push(`  - \`${alias}\` → \`${paths[0]}\``);
        }
      }

      return sections.length > 0 ? sections.join('\n') : '';
    } catch {
      return '';
    }
  }
}

// ============================================================================
// Factory Function
// ============================================================================

/**
 * Create a KI manager for a workspace.
 */
export function createKIManager(
  workspacePath: string,
  options: Partial<KIManagerConfig> = {}
): KnowledgeItemManager {
  return new KnowledgeItemManager({
    workspacePath,
    maxContextTokens: options.maxContextTokens ?? 4000,
    enableAutoDiscovery: options.enableAutoDiscovery ?? true,
  });
}

export default KnowledgeItemManager;
